var res = {
    MainMap_png : "res/map_ver3_noon.png"
    , Allow_png : "res/arrow.png"
    , Yajirushi : "res/Yajirushi.png"
    , IconMove : "res/command_move.png"
    , IconGet : "res/command_get.png"
    , IconChange : "res/command_change.png"
    , IconItem : "res/command_item.png"
    , IconMove2 : "res/command_move2.png"
    , IconGet2 : "res/command_get2.png"
    , IconChange2 : "res/command_change2.png"
    , IconItem2 : "res/command_item2.png"
    , Dice1 : "res/dice1.png"
    , Dice2 : "res/dice2.png"
    , Dice3 : "res/dice3.png"
    , Dice4 : "res/dice4.png"
    , Dice5 : "res/dice5.png"
    , Dice6 : "res/dice6.png"
    , CardArrow : "res/ItemArrow.png"
    , CardPolice : "res/ItemPolice.png"
    , CardPeople : "res/ItemPeople.png"
    , PoliceIcon : "res/police.png"
    , Player1_png : "res/koma_red.png"
    , CollectedMenu : "res/menuCollected.png"
    , Collected1 : "res/collected1.png"
    , Collected2 : "res/collected2.png"
    , Collected3 : "res/collected3.png"
    , Collected4 : "res/collected4.png"
    , Collected5 : "res/collected5.png"
    , Collected6 : "res/collected6.png"
    , Collected7 : "res/collected7.png"
    , Collected8 : "res/collected8.png"
    , Collected9 : "res/collected9.png"
    , PocketMenu : "res/menuPocket.png"
    , Pocket1 : "res/pocket1.png"
    , Pocket2 : "res/pocket2.png"
    , Pocket3 : "res/pocket3.png"
    , Pocket4 : "res/pocket4.png"
    , Pocket5 : "res/pocket5.png"
    , Pocket6 : "res/pocket6.png"
    , Pocket7 : "res/pocket7.png"
    , Pocket8 : "res/pocket8.png"
    , Pocket9 : "res/pocket9.png"
    , UsedMenu : "res/menuUsed.png"
    , DisableMark : "res/overray_disabled.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}