var res = {
    MainMap_png : "res/map_ver4.png"
    , Allow_png : "res/arrow.png"
    , Yajirushi : "res/arrowsign.png"
    , IconMove : "res/command_move.png"
    , IconGet : "res/command_get.png"
    , IconChange : "res/command_change.png"
    , IconItem : "res/command_item.png"
    , IconMove2 : "res/command_move2.png"
    , IconGet2 : "res/command_get2.png"
    , IconChange2 : "res/command_change2.png"
    , IconItem2 : "res/command_item2.png"
    , Dice1 : "res/dice1.png"
    , Dice2 : "res/dice2.png"
    , Dice3 : "res/dice3.png"
    , Dice4 : "res/dice4.png"
    , Dice5 : "res/dice5.png"
    , Dice6 : "res/dice6.png"
    , CardArrow : "res/ItemArrow.png"
    , CardPolice : "res/ItemPolice.png"
    , CardPeople : "res/ItemPeople.png"
    , PoliceIcon : "res/police.png"
    , Player1_png : "res/koma_red.png"
    , Player2_png : "res/koma_green.png"
    , Player3_png : "res/koma_blue.png"
    , Player4_png : "res/koma_yellow.png"
    , CollectedMenu : "res/menuCollected.png"
    , Collected1 : "res/collected1.png"
    , Collected2 : "res/collected2.png"
    , Collected3 : "res/collected3.png"
    , Collected4 : "res/collected4.png"
    , Collected5 : "res/collected5.png"
    , Collected6 : "res/collected6.png"
    , Collected7 : "res/collected7.png"
    , Collected8 : "res/collected8.png"
    , Collected9 : "res/collected9.png"
    , PocketMenu : "res/menuPocket.png"
    , Pocket1 : "res/pocket1.png"
    , Pocket2 : "res/pocket2.png"
    , Pocket3 : "res/pocket3.png"
    , Pocket4 : "res/pocket4.png"
    , Pocket5 : "res/pocket5.png"
    , Pocket6 : "res/pocket6.png"
    , Pocket7 : "res/pocket7.png"
    , Pocket8 : "res/pocket8.png"
    , Pocket9 : "res/pocket9.png"
    , UsedMenu : "res/menuUsed.png"
    , DisableMark : "res/overray_disabled.png"
    , Girl1 : "res/girl_no1.png"
    , Girl2 : "res/girl_no2.png"
    , Girl3 : "res/girl_no3.png"
    , Girl4 : "res/girl_no4.png"
    , Girl5 : "res/girl_no5.png"
    , Girl6 : "res/girl_no6.png"
    , Girl7 : "res/girl_no7.png"
    , Girl8 : "res/girl_no8.png"
    , Girl9 : "res/girl_no9.png"
    , CutinForfeitPolice: "res/cutin/forfeit_police.png"
    , CutinForfeitGirl01: "res/cutin/cutin_forfeit_girl01.png"
    , CutinForfeitGirl02: "res/cutin/cutin_forfeit_girl02.png"
    , CutinForfeitGirl03: "res/cutin/cutin_forfeit_girl03.png"
    , CutinForfeitGirl04: "res/cutin/cutin_forfeit_girl04.png"
    , CutinForfeitGirl05: "res/cutin/cutin_forfeit_girl05.png"
    , CutinForfeitGirl06: "res/cutin/cutin_forfeit_girl06.png"
    , CutinForfeitGirl07: "res/cutin/cutin_forfeit_girl07.png"
    , CutinForfeitGirl08: "res/cutin/cutin_forfeit_girl08.png"
    , CutinForfeitGirl09: "res/cutin/cutin_forfeit_girl09.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}